name: blackjack
version: 0.1.0.0
github: "beefyhalo/blackjack"
license: BSD-3-Clause
author: "Kevin Horlick"
maintainer: "example@example.com"
copyright: "2025 Kevin Horlick"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/beefyhalo/blackjack#readme>

language: GHC2021

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - random
  - mtl
  - crem
  - singletons-base
  - containers
  - list-shuffle
  - array
  - vector
  - generic-override
  - profunctors
  - nonempty-zipper
  - text

executables:
  blackjack-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blackjack
    - crem
    - random

tests:
  blackjack-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blackjack
    - crem
    - hedgehog
    - text
    - mmorph
    - exceptions
    - mtl
    - transformers
    - random
    - containers
